### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by vsheg** [lilyminium/psiresp#103]
Please update the examples link in the README, it points to the 404.

> Examples for PsiRESP are provided as tutorials both [online](https://psiresp.readthedocs.io/en/latest/examples/README.html) and as downloadable Jupyter notebooks in the [examples folder](https://github.com/lilyminium/psiresp/tree/review-updates/docs/source/examples)

**Comment by lilyminium** [comment]
Thanks for that @vsheg, and sorry for the delay in seeing this. I've fixed the link now.
