### ISSUE TITLE
Off-center partial charges

### ISSUE THREAD

**Issue by EBGU** [lilyminium/psiresp#105]
**Is your feature request related to a problem? Please describe.**

I wonder if this package can fit off-center partial charges for lone pairs and sigma holes. Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lilyminium** [comment]
Hi @EBGU! Right now there is no straightforward way to run the pipeline for off-centered charges, as everything is centered around full atom particles. A pull request to add this functionality would be very welcome!
