### ISSUE TITLE
Potential issue displaying job progress

### ISSUE THREAD

**Issue by ptmerz** [lilyminium/psiresp#73]
This is definitely minor, but I thought I'd mention it in case it's an easy fix. When running the examples in the documentation (both for the single and the multi molecular case), when I would run the actual job,

```job.run(client=client)```

the output

```generate-conformers: 100%|█████████████████████████████| 1/1 [00:00<00:00, 276.27it/s]```

would appear immediately, followed by a long-ish break, after which the second output 

```compute-esp: 100%|█████████████████████████████| 1/1 [00:00<00:00, 16.75it/s]```

would appear, immediately at 100%. I was wondering whether
* this is due to the simple example, and the bar would appear gradually for more complex examples, or
* if there is a small bug which keeps the bar from being filled gradually over the calculation, or
* if there is another long step in between the two which does not display any progress information.

I observed this running the examples both in a Jupyter notebook and directly in a Python terminal.

Ref: JOSS review at https://github.com/openjournals/joss-reviews/issues/4100

**Comment by lilyminium** [comment]
Thanks @ptmerz! You're right, there are some long steps where QCFractal is waiting for Psi4 to complete, which were not given progress bars. Thanks to the great tqdm library it is fairly easy to fix this, and I've added progress bars in #75. As you've said that this is not a blocking problem, I will merge as-is so as not to take up more of your time, but please do let me know if this is not the best solution!

**Comment by ptmerz** [comment]
Your changes look great, thanks for addressing this!
